[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_APP_URL = "https://grant-assistant.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_APP_URL = "https://deploy-preview--grant-assistant.netlify.app"

[context.branch-deploy.environment]
  NEXT_PUBLIC_APP_URL = "https://branch--grant-assistant.netlify.app"